# Generated by Django 6.0.1 on 2026-01-24 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('bloque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.bloque')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='menus/')),
                ('cafeteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cafeterias.cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='cafeterias.cafeteria')),
            ],
        ),
    ]
