# Generated by Django 5.2.10 on 2026-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0002_alter_resena_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
