
# Generated by Django 6.0.1 on 2026-01-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_mesareserva_id_alter_reserva_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesareserva',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='LIBRE', max_length=15),
        ),
    ]
